# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# .github/workflows/python-app.yml 파일 내용 (파일명은 그대로 사용)

name: Python-app.yml # 워크플로 이름. 좀 더 명확하게 변경 (선택 사항)

on:
  push:
    branches: [ "main" ] # 메인 브랜치 이름이 'main'인지 확인 
  pull_request:
    branches: [ "main" ] # 위와 동일하게 브랜치 이름 확인

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5 # 최신 액션 버전인 v5 사용
      with:
        python-version: "3.10" # 사용할 Python 버전 지정(프로젝트에 맞는 버전으로 변경 가능)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest
